#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Text-Tiki
version:      0.73
version_from: Tiki.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
